# Generated by Django 2.1.7 on 2020-05-15 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('topic', models.CharField(max_length=100, null=True)),
                ('crawlDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
